Repository istio/envoy, pull requests merged in 2019-08, with the labels that each got.

#89 Set release managers as CODEOWNERS for release-1.3
  CODEOWNERS
Labels: cla: yes, size/S

#91 network: fix misaligned memory access in setsockopt().
  source/common/network/socket_option_impl.cc
  source/common/network/socket_option_impl.h
  test/common/network/socket_option_impl_test.cc
Labels: cla: yes, size/S

#92 network: fix misaligned memory access in setsockopt().
  source/common/network/socket_option_impl.cc
  source/common/network/socket_option_impl.h
  test/common/network/socket_option_factory_test.cc
  test/common/network/socket_option_impl_test.cc
Labels: cla: yes, size/M

#93 network: fix misaligned memory access in setsockopt().
  source/common/network/socket_option_impl.cc
  source/common/network/socket_option_impl.h
  test/common/network/socket_option_factory_test.cc
  test/common/network/socket_option_impl_test.cc
Labels: cla: yes, size/M

#99 fix upstream host NULL pointer
  source/extensions/common/wasm/wasm.cc
Labels: cla: yes, size/XS

#95 Do not 503 on Upgrade: h2c instead remove the header and ignore.
  source/common/common/utility.cc
  source/common/common/utility.h
  source/common/http/headers.h
  source/common/http/http1/codec_impl.cc
  test/common/common/utility_speed_test.cc
  test/common/common/utility_test.cc
  test/common/http/http1/codec_impl_test.cc
Labels: cla: yes, size/L

#98 Do not 503 on Upgrade: h2c instead remove the header and ignore.
  source/common/common/utility.cc
  source/common/common/utility.h
  source/common/http/headers.h
  source/common/http/http1/codec_impl.cc
  test/common/common/utility_speed_test.cc
  test/common/common/utility_test.cc
  test/common/http/http1/codec_impl_test.cc
Labels: cla: yes, size/L

#96 Add .bazelversion for bazelisk support.
  .bazelversion
Labels: cla: yes, size/XS

#97 Add .bazelversion for bazelisk support.
  .bazelversion
Labels: cla: yes, size/XS
