Repository istio/envoy, pull requests merged in 2019-09, with the labels that each got.

#101 Do not 503 on Upgrade: h2c instead remove the header and ignore. (#7981)
  docs/root/intro/version_history.rst
  source/common/common/utility.cc
  source/common/common/utility.h
  source/common/http/headers.h
  source/common/http/http1/codec_impl.cc
  test/common/common/utility_speed_test.cc
  test/common/common/utility_test.cc
  test/common/http/http1/codec_impl_test.cc
Labels: cla: yes, size/L

#102 fix random sample fraction percent
  source/extensions/filters/network/http_connection_manager/config.cc
  test/extensions/filters/network/http_connection_manager/config_test.cc
Labels: cla: yes, size/M

#107 Fix segfault by ensuring that we have created the context in the VM. …
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  source/extensions/filters/http/wasm/wasm_filter.h
Labels: cla: yes, size/S

#108 Wasm dockerfile (#174)
  WASM.md
  api/wasm/cpp/Dockerfile-sdk
  api/wasm/cpp/Makefile.base
  api/wasm/cpp/Makefile.base_lite
  api/wasm/cpp/README.md
  api/wasm/cpp/build_wasm.sh
  api/wasm/cpp/sdk_container.sh
  api/wasm/rust/README.md
Labels: cla: yes, size/L

#106 Update dependency: jwt_verify_lib
  bazel/repository_locations.bzl
Labels: cla: yes, size/XS
