Repository istio/envoy, pull requests merged in 2019-11, with the labels that each got.

#114 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/M

#115 [release-1.4] build: update wee8 to 7.9.317.14. (#287)
  bazel/repository_locations.bzl
Labels: cla: yes, size/XS

#116 Add response flags into cel expression context (#8827)
  docs/root/intro/arch_overview/security/rbac_filter.rst
  include/envoy/stream_info/stream_info.h
  source/common/stream_info/stream_info_impl.h
  source/extensions/filters/common/expr/BUILD
  source/extensions/filters/common/expr/context.cc
  source/extensions/filters/common/expr/context.h
  test/common/stream_info/stream_info_impl_test.cc
  test/common/stream_info/test_util.h
  test/extensions/filters/common/expr/context_test.cc
  test/mocks/stream_info/mocks.h
Labels: cla: yes, size/S

#117 [release-1.4] update opencensus sha (#8908)
  bazel/repository_locations.bzl
Labels: cla: yes, size/XS

#118 listener: clean up accept filters before connection creation
  source/server/connection_handler_impl.cc
Labels: cla: yes, size/XS

#119 [1.4] listener: clean up accept filters before connection creation
  source/server/connection_handler_impl.cc
Labels: cla: yes, size/XS

#120 http inspector: use http_parser in http inspector (#8808)
  source/extensions/filters/listener/http_inspector/BUILD
  source/extensions/filters/listener/http_inspector/http_inspector.cc
  source/extensions/filters/listener/http_inspector/http_inspector.h
  source/extensions/filters/listener/http_inspector/http_protocol_header.h
  test/extensions/filters/listener/http_inspector/http_inspector_test.cc
Labels: cla: yes, size/L

#121 Make wasm state serializable.
  api/envoy/config/accesslog/v2/als.proto
  api/envoy/config/accesslog/v3alpha/als.proto
  api/envoy/data/accesslog/v2/accesslog.proto
  api/envoy/data/accesslog/v3alpha/accesslog.proto
  docs/root/configuration/observability/access_log.rst
  docs/root/intro/arch_overview/advanced/data_sharing_between_filters.rst
  include/envoy/stream_info/BUILD
  include/envoy/stream_info/filter_state.h
  source/common/access_log/access_log_formatter.cc
  source/common/access_log/access_log_formatter.h
  source/common/router/string_accessor_impl.h
  source/extensions/access_loggers/grpc/BUILD
  source/extensions/access_loggers/grpc/grpc_access_log_utils.cc
  source/extensions/access_loggers/grpc/grpc_access_log_utils.h
  source/extensions/access_loggers/grpc/http_grpc_access_log_impl.cc
  source/extensions/access_loggers/grpc/http_grpc_access_log_impl.h
  source/extensions/access_loggers/grpc/tcp_grpc_access_log_impl.cc
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/wasm_state.cc
  source/extensions/common/wasm/wasm_state.h
  test/common/access_log/BUILD
  test/common/access_log/access_log_formatter_test.cc
  test/extensions/access_loggers/grpc/BUILD
  test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc
Labels: cla: yes, size/L

#122 [release-1.4] bazel: replace tclap mirror. (#9072)
  bazel/repositories.bzl
  bazel/repository_locations.bzl
Labels: size/S

#125 [release-1.1] bazel: replace tclap mirror. (#9072)
  bazel/repositories.bzl
  bazel/repository_locations.bzl
Labels: cla: yes, size/S

#123 [release-1.3] bazel: replace tclap mirror. (#9072)
  bazel/repositories.bzl
  bazel/repository_locations.bzl
Labels: cla: yes, size/S

#124 [release-1.2] bazel: replace tclap mirror. (#9072)
  bazel/repositories.bzl
  bazel/repository_locations.bzl
Labels: cla: yes, size/S
