Repository istio/envoy, pull requests merged in 2020-07, with the labels that each got.

#231 tls: improve wildcard matching (#11921) (#11927)
  VERSION
  docs/root/intro/version_history.rst
  source/common/runtime/runtime_features.cc
  source/extensions/transport_sockets/tls/BUILD
  source/extensions/transport_sockets/tls/context_impl.cc
  test/extensions/transport_sockets/tls/BUILD
  test/extensions/transport_sockets/tls/context_impl_test.cc
Labels: cla: yes, size/M

#232 tls: improve wildcard matching (#11921) (#11928)
  VERSION
  docs/root/intro/version_history.rst
  source/common/runtime/runtime_features.cc
  source/extensions/transport_sockets/tls/BUILD
  source/extensions/transport_sockets/tls/context_impl.cc
  test/extensions/transport_sockets/tls/BUILD
  test/extensions/transport_sockets/tls/context_impl_test.cc
Labels: cla: yes, size/L

#233 tls: improve wildcard matching (#11921) (#11929)
  VERSION
  docs/root/intro/version_history.rst
  source/common/runtime/runtime_features.cc
  source/extensions/transport_sockets/tls/BUILD
  source/extensions/transport_sockets/tls/context_impl.cc
  test/extensions/transport_sockets/tls/BUILD
  test/extensions/transport_sockets/tls/context_impl_test.cc
Labels: cla: yes, size/M

#236 tls: update BoringSSL-FIPS to 20190808.
  api/envoy/api/v2/auth/cert.proto
  api/envoy/extensions/transport_sockets/tls/v3/cert.proto
  bazel/external/boringssl_fips.genrule_cmd
  bazel/external/boringssl_fips.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  docs/root/intro/arch_overview/security/ssl.rst
  generated_api_shadow/envoy/api/v2/auth/cert.proto
  generated_api_shadow/envoy/extensions/transport_sockets/tls/v3/cert.proto
  source/extensions/transport_sockets/tls/context_config_impl.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
Labels: cla: yes, size/M

#237 tls: update BoringSSL-FIPS to 20190808.
  api/envoy/api/v2/auth/cert.proto
  api/envoy/api/v3alpha/auth/cert.proto
  bazel/external/boringssl_fips.genrule_cmd
  bazel/external/boringssl_fips.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  docs/root/intro/arch_overview/security/ssl.rst
  source/extensions/transport_sockets/tls/context_config_impl.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
Labels: cla: yes, size/M

#235 tls: update BoringSSL-FIPS to 20190808.
  api/envoy/api/v2/auth/cert.proto
  api/envoy/extensions/transport_sockets/tls/v3/cert.proto
  api/envoy/extensions/transport_sockets/tls/v4alpha/cert.proto
  bazel/external/boringssl_fips.genrule_cmd
  bazel/external/boringssl_fips.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  docs/root/intro/arch_overview/security/ssl.rst
  generated_api_shadow/envoy/api/v2/auth/cert.proto
  generated_api_shadow/envoy/extensions/transport_sockets/tls/v3/cert.proto
  generated_api_shadow/envoy/extensions/transport_sockets/tls/v4alpha/cert.proto
  source/extensions/transport_sockets/tls/context_config_impl.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
Labels: cla: yes, size/M

#238 Revert unnecessary and incompatible change to genrule_repository.
  bazel/external/wee8.patch
  bazel/genrule_repository.bzl
Labels: cla: yes, size/S

#234 Make opencensus Stackdriver exporter respects initial_metadata option…
  bazel/repository_locations.bzl
  source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
  test/extensions/tracers/opencensus/config_test.cc
Labels: cla: yes, size/M

#244 dns filter: fix asan test
  source/extensions/filters/udp/dns_filter/dns_filter.cc
  source/extensions/filters/udp/dns_filter/dns_filter.h
  source/extensions/filters/udp/dns_filter/dns_filter_resolver.h
Labels: cla: yes, size/S

#239 Set release managers as CODEOWNERS for release-1.7
  CODEOWNERS
Labels: cla: yes, size/L

#245 [release-1.7] load stats: fix integration test flake (#12265)
  source/common/upstream/load_stats_reporter.cc
  test/integration/README.md
Labels: cla: yes, size/XS

#242 [release-1.7] sync envoy-wasm
  api/envoy/data/dns/v3/dns_table.proto
  api/envoy/data/dns/v4alpha/dns_table.proto
  bazel/repositories.bzl
  generated_api_shadow/envoy/data/dns/v3/dns_table.proto
  generated_api_shadow/envoy/data/dns/v4alpha/dns_table.proto
  source/extensions/common/wasm/context.cc
Labels: cla: yes, size/S

#246 cherry-pick ECDS
  api/BUILD
  api/envoy/config/accesslog/v3/accesslog.proto
  api/envoy/config/accesslog/v4alpha/accesslog.proto
  api/envoy/config/core/v3/extension.proto
  api/envoy/config/core/v4alpha/extension.proto
  api/envoy/data/accesslog/v3/accesslog.proto
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  api/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  api/envoy/service/extension/v3/BUILD
  api/envoy/service/extension/v3/config_discovery.proto
  api/versioning/BUILD
  docs/root/api-v3/service/service.rst
  docs/root/configuration/overview/extension.rst
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/config/accesslog/v3/accesslog.proto
  generated_api_shadow/envoy/config/accesslog/v4alpha/accesslog.proto
  generated_api_shadow/envoy/config/core/v3/extension.proto
  generated_api_shadow/envoy/config/core/v4alpha/extension.proto
  generated_api_shadow/envoy/data/accesslog/v3/accesslog.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  generated_api_shadow/envoy/service/extension/v3/BUILD
  generated_api_shadow/envoy/service/extension/v3/config_discovery.proto
  include/envoy/config/BUILD
  include/envoy/config/extension_config_provider.h
  include/envoy/filter/http/BUILD
  include/envoy/filter/http/filter_config_provider.h
  include/envoy/stream_info/stream_info.h
  source/common/config/BUILD
  source/common/config/protobuf_link_hacks.h
  source/common/config/type_to_endpoint.cc
  source/common/config/utility.h
  source/common/filter/http/BUILD
  source/common/filter/http/filter_config_discovery_impl.cc
  source/common/filter/http/filter_config_discovery_impl.h
  source/common/stream_info/utility.cc
  source/common/stream_info/utility.h
  source/extensions/access_loggers/grpc/grpc_access_log_utils.cc
  source/extensions/filters/network/http_connection_manager/BUILD
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  test/common/access_log/access_log_impl_test.cc
  test/common/filter/http/BUILD
  test/common/filter/http/filter_config_discovery_impl_test.cc
  test/common/stream_info/utility_test.cc
  test/extensions/access_loggers/grpc/grpc_access_log_utils_test.cc
  test/extensions/filters/network/http_connection_manager/BUILD
  test/extensions/filters/network/http_connection_manager/config_test.cc
  test/integration/BUILD
  test/integration/extension_discovery_integration_test.cc
Labels: cla: yes, size/XXL

#247 tls: update BoringSSL-FIPS to 20190808. (#12170)
  api/envoy/api/v2/auth/common.proto
  api/envoy/extensions/transport_sockets/tls/v3/common.proto
  api/envoy/extensions/transport_sockets/tls/v4alpha/common.proto
  bazel/external/boringssl_fips.genrule_cmd
  bazel/external/boringssl_fips.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  docs/root/intro/arch_overview/security/ssl.rst
  generated_api_shadow/envoy/api/v2/auth/common.proto
  generated_api_shadow/envoy/extensions/transport_sockets/tls/v3/common.proto
  generated_api_shadow/envoy/extensions/transport_sockets/tls/v4alpha/common.proto
  source/extensions/transport_sockets/tls/context_config_impl.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
Labels: cla: yes, size/M
