Repository istio/envoy, pull requests merged in 2020-02, with the labels that each got.

#136 Response total size
  docs/root/intro/arch_overview/security/rbac_filter.rst
  source/extensions/filters/common/expr/BUILD
  source/extensions/filters/common/expr/context.cc
  test/extensions/filters/common/expr/context_test.cc
Labels: cla: yes, size/M

#138 Fix TSAN race.
  source/extensions/common/wasm/v8/v8.cc
Labels: cla: yes, size/XS

#140 wasm: drop wasm_opt flag, it trips TSan and benefits are unclear. (#380)
  source/extensions/common/wasm/v8/v8.cc
  test/extensions/common/wasm/test_data/test_rust.wasm
  test/tools/wee8_compile/wee8_compile.cc
Labels: cla: yes, size/S

#141 implement expression evaluation in Wasm (#345)
  WORKSPACE
  api/wasm/cpp/contrib/BUILD
  api/wasm/cpp/contrib/proxy_expr.h
  bazel/antlr.patch
  bazel/repositories.bzl
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/foreign.cc
  test/extensions/filters/http/wasm/test_data/async_call_cpp.wasm
  test/extensions/filters/http/wasm/test_data/grpc_call_cpp.wasm
  test/extensions/filters/http/wasm/test_data/grpc_callout_cpp.wasm
  test/extensions/filters/http/wasm/test_data/headers_cpp.wasm
  test/extensions/filters/http/wasm/test_data/http_callout_cpp.wasm
  test/extensions/filters/http/wasm/test_data/metadata_cpp.cc
  test/extensions/filters/http/wasm/test_data/metadata_cpp.wasm
  test/extensions/filters/http/wasm/test_data/queue_cpp.wasm
  test/extensions/filters/http/wasm/test_data/shared_cpp.wasm
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/L

#142 Cherry-pick filter state PRs needed for TCP telemetry
  include/envoy/stream_info/filter_state.h
  include/envoy/stream_info/stream_info.h
  source/common/router/router.cc
  source/common/stream_info/stream_info_impl.h
  source/common/tcp_proxy/tcp_proxy.cc
  source/extensions/common/wasm/context.cc
  source/extensions/filters/http/grpc_stats/grpc_stats_filter.cc
  source/extensions/filters/http/jwt_authn/filter.cc
  source/extensions/filters/network/sni_cluster/sni_cluster.cc
  test/common/access_log/access_log_formatter_test.cc
  test/common/http/conn_manager_impl_test.cc
  test/common/router/header_formatter_test.cc
  test/common/router/router_test.cc
  test/common/stream_info/stream_info_impl_test.cc
  test/common/stream_info/test_util.h
  test/common/tcp_proxy/tcp_proxy_test.cc
  test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc
  test/extensions/filters/http/grpc_stats/config_test.cc
  test/extensions/filters/http/jwt_authn/filter_integration_test.cc
  test/extensions/filters/network/sni_cluster/sni_cluster_test.cc
  test/mocks/stream_info/mocks.cc
  test/mocks/stream_info/mocks.h
Labels: cla: yes, size/XL

#143 Return the foreign function result.
  source/extensions/common/wasm/exports.cc
Labels: cla: yes, size/XS

#144 Use sts for call credential when STS_PORT is provided in node metadata
  source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
Labels: cla: yes, size/S

#146 [release-1.5] add ignore_case to StringMatcher that allows case insensitive exact/prefix/suffix string matching
  api/envoy/type/matcher/string.proto
  api/envoy/type/matcher/v3/string.proto
  generated_api_shadow/envoy/type/matcher/string.proto
  generated_api_shadow/envoy/type/matcher/v3/string.proto
  source/common/common/matchers.cc
  test/common/common/BUILD
  test/common/common/matchers_test.cc
Labels: cla: yes, size/M

#145 Upgrade gRPC to 1.25 which has gRPC STS feature
  bazel/dependency_imports.bzl
  bazel/grpc-protoinfo-1.patch
  bazel/grpc-protoinfo-2.patch
  bazel/grpc-protoinfo-3.patch
  bazel/grpc-rename-gettid.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  bazel/upb.patch
  source/common/http/async_client_impl.h
Labels: cla: yes, size/L

#148 [release-1.4] Use sts for call credential when STS_PORT is provided in node metadata #144
  source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
Labels: cla: yes, size/S

#147 matcher: add PathMatcher and use in routing, jwt and rbac
  VERSION
  api/envoy/config/rbac/v2/rbac.proto
  api/envoy/config/rbac/v3/rbac.proto
  api/envoy/type/matcher/path.proto
  api/envoy/type/matcher/v3/path.proto
  docs/root/api-v2/types/types.rst
  docs/root/api-v3/types/types.rst
  docs/root/intro/version_history.rst
  generated_api_shadow/envoy/config/rbac/v2/rbac.proto
  generated_api_shadow/envoy/config/rbac/v3/rbac.proto
  generated_api_shadow/envoy/type/matcher/path.proto
  generated_api_shadow/envoy/type/matcher/v3/path.proto
  source/common/common/BUILD
  source/common/common/matchers.cc
  source/common/common/matchers.h
  source/common/http/path_utility.cc
  source/common/http/path_utility.h
  source/common/router/BUILD
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  source/extensions/filters/common/rbac/matchers.cc
  source/extensions/filters/common/rbac/matchers.h
  source/extensions/filters/http/jwt_authn/BUILD
  source/extensions/filters/http/jwt_authn/matcher.cc
  test/common/common/matchers_test.cc
  test/common/http/path_utility_test.cc
  test/extensions/filters/common/rbac/matchers_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/extensions/filters/http/rbac/rbac_filter_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/XL

#149 Pick up a gRPC STS fix.
  bazel/repository_locations.bzl
Labels: cla: yes, size/XS

#151 Fix tracer ssl credential
  source/extensions/tracers/opencensus/config.cc
  source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
  source/extensions/tracers/opencensus/opencensus_tracer_impl.h
  test/extensions/filters/common/expr/context_test.cc
Labels: cla: yes, size/S

#153 Update GrpcService to add StsService. (#411)
  api/wasm/cpp/proxy_wasm_intrinsics.pb.cc
  api/wasm/cpp/proxy_wasm_intrinsics.pb.h
  api/wasm/cpp/proxy_wasm_intrinsics.proto
  api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.cc
  api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.h
  api/wasm/cpp/proxy_wasm_intrinsics_lite.proto
Labels: cla: yes, size/XXL

#154 Update GrpcService to add StsService. (#411)
  api/wasm/cpp/proxy_wasm_intrinsics.pb.cc
  api/wasm/cpp/proxy_wasm_intrinsics.pb.h
  api/wasm/cpp/proxy_wasm_intrinsics.proto
  api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.cc
  api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.h
  api/wasm/cpp/proxy_wasm_intrinsics_lite.proto
Labels: cla: yes, size/XXL

#150 Add upstream and downstream info in parent read callbacks in tcp too(#9949)
  source/common/network/connection_impl.cc
  source/common/network/connection_impl.h
  source/common/tcp_proxy/tcp_proxy.cc
  source/common/tcp_proxy/tcp_proxy.h
  source/extensions/filters/network/tcp_proxy/config.cc
  test/common/http/conn_manager_impl_test.cc
  test/common/network/filter_manager_impl_test.cc
  test/common/stream_info/BUILD
  test/common/stream_info/test_util.h
  test/common/tcp_proxy/tcp_proxy_test.cc
  test/common/upstream/health_checker_impl_test.cc
  test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc
  test/extensions/filters/http/lua/lua_filter_test.cc
  test/extensions/filters/http/lua/wrappers_test.cc
  test/extensions/filters/network/tcp_proxy/config_test.cc
  test/extensions/tracers/zipkin/zipkin_tracer_impl_test.cc
  test/mocks/stream_info/BUILD
  test/mocks/stream_info/mocks.cc
  test/mocks/stream_info/mocks.h
Labels: cla: yes, size/L

#152 Add x-goog-user-proj header for sts credential
  api/wasm/cpp/proxy_wasm_api.h
  source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
Labels: cla: yes, size/M

#155 Fix opencensus tracer test
  test/extensions/tracers/opencensus/tracer_test.cc
Labels: cla: yes, size/XS

#157 Cache and share the base Wasm VM.
  bazel/repository_locations.bzl
  source/extensions/access_loggers/wasm/config.cc
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  source/extensions/filters/http/wasm/wasm_filter.cc
  source/extensions/filters/network/wasm/wasm_filter.cc
  source/extensions/wasm/config.cc
  test/extensions/access_loggers/wasm/config_test.cc
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
  test/extensions/wasm/config_test.cc
  test/extensions/wasm/wasm_speed_test.cc
  test/extensions/wasm/wasm_test.cc
Labels: cla: yes, size/L

#156 [release-1.5] Fix opencensus tracer for sts
  source/extensions/tracers/opencensus/config.cc
  source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
  source/extensions/tracers/opencensus/opencensus_tracer_impl.h
  test/extensions/tracers/opencensus/tracer_test.cc
Labels: cla: yes, size/M

#158 [release-1.5] Fix grpc create initial metadata callback
  api/wasm/cpp/proxy_wasm_api.h
  test/extensions/filters/http/wasm/test_data/grpc_call_cpp.cc
  test/extensions/filters/http/wasm/test_data/grpc_call_cpp.wasm
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/M

#162 ci: mark //test/integration:protocol_integration_test as flaky.
  bazel/envoy_test.bzl
  test/integration/BUILD
Labels: cla: yes, size/XS

#161 ci: stop testing integration with other workspaces. (#382)
  ci/do_ci.sh
Labels: cla: yes, size/XS

#159 Fix Wasm VM shutdown.
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
Labels: cla: yes, size/M

#160 wasm: remove unused "free" function. (#404)
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
Labels: cla: yes, size/XS

#164 Fix use-after-free error for remote .wasm file accesses. (#427)
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  source/extensions/filters/http/wasm/wasm_filter.cc
  source/extensions/filters/network/wasm/wasm_filter.cc
  source/extensions/wasm/config.cc
  test/extensions/common/wasm/BUILD
  test/extensions/common/wasm/wasm_test.cc
Labels: cla: yes, size/L

#167 ci: increase timeout for a few //test/common/stats:... tests.
  test/common/stats/BUILD
Labels: cla: yes, size/XS

#165 Make send local reply non-reentrant.
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/exports.cc
  source/extensions/common/wasm/wasm.h
Labels: cla: yes, size/M

#166 Make callout responses accessible from stream context. (#429)
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/exports.cc
  source/extensions/common/wasm/foreign.cc
  test/extensions/filters/http/wasm/test_data/async_call_cpp.cc
  test/extensions/filters/http/wasm/test_data/async_call_cpp.wasm
Labels: cla: yes, size/M

#169 Add proxy_abi_version_X_Y_Z and mark what we have as v0.1.0. (#438)
  api/wasm/cpp/proxy_wasm_intrinsics.cc
  examples/wasm/envoy_filter_http_wasm_example.wasm
  source/extensions/common/wasm/null/null_plugin.cc
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  test/extensions/access_loggers/wasm/test_data/logging.wasm
  test/extensions/common/wasm/test_data/bad_signature_cpp.cc
  test/extensions/common/wasm/test_data/bad_signature_cpp.wasm
  test/extensions/common/wasm/test_data/test_cpp.cc
  test/extensions/common/wasm/test_data/test_cpp.wasm
  test/extensions/common/wasm/test_data/test_rust.wasm
  test/extensions/filters/http/wasm/test_data/async_call_cpp.wasm
  test/extensions/filters/http/wasm/test_data/grpc_call_cpp.wasm
  test/extensions/filters/http/wasm/test_data/grpc_callout_cpp.wasm
  test/extensions/filters/http/wasm/test_data/headers_cpp.wasm
  test/extensions/filters/http/wasm/test_data/http_callout_cpp.wasm
  test/extensions/filters/http/wasm/test_data/metadata_cpp.wasm
  test/extensions/filters/http/wasm/test_data/queue_cpp.wasm
  test/extensions/filters/http/wasm/test_data/shared_cpp.wasm
  test/extensions/filters/network/wasm/test_data/logging_cpp.wasm
  test/extensions/wasm/test_data/asm2wasm_cpp.cc
  test/extensions/wasm/test_data/asm2wasm_cpp.wasm
  test/extensions/wasm/test_data/bad_signature_cpp.cc
  test/extensions/wasm/test_data/bad_signature_cpp.wasm
  test/extensions/wasm/test_data/emscripten_cpp.cc
  test/extensions/wasm/test_data/emscripten_cpp.wasm
  test/extensions/wasm/test_data/logging_cpp.cc
  test/extensions/wasm/test_data/logging_cpp.wasm
  test/extensions/wasm/test_data/logging_rust.wasm
  test/extensions/wasm/test_data/logging_rust/src/lib.rs
  test/extensions/wasm/test_data/missing_cpp.cc
  test/extensions/wasm/test_data/missing_cpp.wasm
  test/extensions/wasm/test_data/segv_cpp.cc
  test/extensions/wasm/test_data/segv_cpp.wasm
  test/extensions/wasm/test_data/speed_cpp.cc
  test/extensions/wasm/test_data/speed_cpp.wasm
  test/extensions/wasm/test_data/start_cpp.cc
  test/extensions/wasm/test_data/start_cpp.wasm
  test/extensions/wasm/test_data/stats_cpp.cc
  test/extensions/wasm/test_data/stats_cpp.wasm
Labels: cla: yes, size/M
