Repository istio/envoy, pull requests merged in 2020-06, with the labels that each got.

#218 [http codec] case-insensetive transfer-encoding checks (#10055)
  source/common/http/http1/codec_impl.cc
  test/common/http/http1/codec_impl_test.cc
Labels: cla: yes, size/S

#219 [release-1.5] zipkin: add key name to prevent bad replacements (#11374)
  source/extensions/tracers/zipkin/span_buffer.cc
  source/extensions/tracers/zipkin/util.cc
  source/extensions/tracers/zipkin/util.h
  source/extensions/tracers/zipkin/zipkin_core_types.cc
  test/extensions/tracers/zipkin/span_buffer_test.cc
Labels: cla: yes, size/M

#220 [release-1.6] zipkin: add key name to prevent bad replacements (#11374)
  source/extensions/tracers/zipkin/span_buffer.cc
  source/extensions/tracers/zipkin/util.cc
  source/extensions/tracers/zipkin/util.h
  source/extensions/tracers/zipkin/zipkin_core_types.cc
  test/extensions/tracers/zipkin/span_buffer_test.cc
Labels: cla: yes, size/M

#222 [1.6] fix flaky test: RetryHostPredicateFilter
  test/integration/http_integration.cc
Labels: cla: yes, size/S

#221 build: bump nghttp2 to 1.41.0. (#11412) (#28)
  bazel/foreign_cc/BUILD
  bazel/repository_locations.bzl
Labels: cla: yes, size/S

#225 build: bump nghttp2 to 1.41.0. (#11412) (#29)
  bazel/foreign_cc/BUILD
  bazel/repository_locations.bzl
Labels: cla: yes, size/S

#226 [1.4] build: bump nghttp2 to 1.41.0. (#11412) (#30)
  bazel/foreign_cc/nghttp2.patch
  bazel/repository_locations.bzl
  source/common/http/http2/codec_impl.cc
  test/integration/http2_integration_test.cc
  tools/spelling_dictionary.txt
Labels: cla: yes, size/L

#227 [release-1.6] fix early deletion of wasm state schema
  source/extensions/common/wasm/context.cc
Labels: cla: yes, size/XS
