Repository istio/envoy, pull requests merged in 2020-01, with the labels that each got.

#131 Update jwt_verify_lib to 2019-12-20
  bazel/repository_locations.bzl
Labels: cla: yes, size/XS

#132 Cherry-pick of https://github.com/envoyproxy/envoy/pull/9839
  docs/root/intro/arch_overview/security/rbac_filter.rst
  source/extensions/filters/common/expr/context.cc
  source/extensions/filters/common/expr/context.h
  test/extensions/filters/common/expr/context_test.cc
Labels: cla: yes, size/S

#133 Cherry-pick of https://github.com/envoyproxy/envoy/pull/9862
  source/extensions/filters/common/expr/context.cc
  test/extensions/filters/common/expr/context_test.cc
Labels: cla: yes, size/M

#134 Update CODEOWNERS for release-1.5
  CODEOWNERS
Labels: cla: yes, size/L
