Repository istio/envoy, pull requests merged in 2020-05, with the labels that each got.

#204 Fetch .wasm from remote URI without depending on Listener.
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/wasm.cc
Labels: cla: yes, size/M

#207 Add stats for wasm remote load fetch and cache.
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/http/wasm/config_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/M

#208 [release-1.6] Wasm remote load cache fix and stats
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/http/wasm/config_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/L

#209 Fix potential cross-thread call to onDone in base Wasm
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
Labels: cla: yes, size/S

#205 Backport listener in place update
  docs/root/configuration/listeners/stats.rst
  include/envoy/network/connection_handler.h
  include/envoy/server/worker.h
  source/common/event/BUILD
  source/common/event/deferred_task.h
  source/common/runtime/runtime_features.cc
  source/extensions/quic_listeners/quiche/active_quic_listener.cc
  source/server/BUILD
  source/server/connection_handler_impl.cc
  source/server/connection_handler_impl.h
  source/server/filter_chain_manager_impl.h
  source/server/http/admin.cc
  source/server/listener_impl.cc
  source/server/listener_impl.h
  source/server/listener_manager_impl.cc
  source/server/listener_manager_impl.h
  source/server/worker_impl.cc
  source/server/worker_impl.h
  test/common/event/BUILD
  test/common/event/dispatcher_impl_test.cc
  test/extensions/common/proxy_protocol/proxy_protocol_regression_test.cc
  test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc
  test/extensions/quic_listeners/quiche/integration/quic_http_integration_test.cc
  test/integration/BUILD
  test/integration/fake_upstream.cc
  test/integration/http2_integration_test.cc
  test/integration/http_integration.h
  test/integration/integration_test.cc
  test/integration/utility.h
  test/integration/xds_integration_test.cc
  test/mocks/network/mocks.h
  test/mocks/server/mocks.cc
  test/mocks/server/mocks.h
  test/server/BUILD
  test/server/connection_handler_test.cc
  test/server/listener_manager_impl_test.cc
  test/server/listener_manager_impl_test.h
  test/server/worker_impl_test.cc
Labels: cla: yes, size/XXL

#211 1.4 - Do not call into the VM unless the VM Context has been created.…
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  test/extensions/wasm/wasm_test.cc
Labels: cla: yes, size/M

#213 1.5 - Do not call into the VM unless the VM Context has been created.…
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  test/extensions/wasm/wasm_test.cc
Labels: cla: yes, size/M

#214 Do not call into the VM unless the VM Context has been created.
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  test/extensions/wasm/wasm_test.cc
Labels: cla: yes, size/M

#216 [release-1.6] fix http call response crash (#455)
  source/extensions/common/wasm/context.cc
Labels: cla: yes, size/XS

#217 [release-1.6] Update cel-cpp to fix CEL seg fault
  bazel/repository_locations.bzl
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/foreign.cc
Labels: cla: yes, size/S
