Repository istio/envoy, pull requests merged in 2020-10, with the labels that each got.

#267 Fix Istio-2020-010
  VERSION
  docs/root/intro/version_history.rst
  include/envoy/http/header_map.h
  source/common/http/BUILD
  source/common/http/header_map_impl.cc
  source/common/http/header_map_impl.h
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/http/http1/codec_impl.cc
  source/common/runtime/BUILD
  source/common/runtime/runtime_features.cc
  source/common/runtime/runtime_features.h
  source/common/runtime/runtime_impl.cc
  source/extensions/common/wasm/context.cc
  source/extensions/filters/common/expr/BUILD
  source/extensions/filters/common/expr/context.cc
  source/extensions/filters/common/expr/context.h
  source/extensions/filters/common/expr/evaluator.cc
  source/extensions/filters/common/expr/evaluator.h
  source/extensions/filters/http/header_to_metadata/BUILD
  source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc
  source/extensions/filters/http/jwt_authn/BUILD
  source/extensions/filters/http/jwt_authn/extractor.cc
  source/extensions/filters/http/lua/BUILD
  source/extensions/filters/http/lua/wrappers.cc
  test/common/http/BUILD
  test/common/http/header_map_impl_test.cc
  test/common/http/header_utility_test.cc
  test/common/http/http1/codec_impl_test.cc
  test/extensions/common/wasm/BUILD
  test/extensions/filters/common/expr/context_test.cc
  test/extensions/filters/common/expr/evaluator_fuzz_test.cc
  test/extensions/filters/http/header_to_metadata/header_to_metadata_filter_test.cc
  test/extensions/filters/http/jwt_authn/extractor_test.cc
  test/extensions/filters/http/lua/wrappers_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/integration/protocol_integration_test.cc
  test/test_common/utility.h
Labels: cla: yes, size/XL

#266 tracing: Fix spankind = CLIENT bug when sharedSpanContext is
  source/extensions/tracers/zipkin/tracer.cc
  test/extensions/tracers/zipkin/tracer_test.cc
Labels: cla: yes, size/M

#268 Fix Istio-2020-010
  VERSION
  docs/root/version_history/current.rst
  docs/root/version_history/v1.15.0.rst
  docs/root/version_history/v1.15.1.rst
  docs/root/version_history/version_history.rst
  include/envoy/http/header_map.h
  source/common/http/BUILD
  source/common/http/header_map_impl.cc
  source/common/http/header_map_impl.h
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/runtime/runtime_features.cc
  source/extensions/common/wasm/context.cc
  source/extensions/filters/common/expr/context.cc
  source/extensions/filters/common/expr/context.h
  source/extensions/filters/common/expr/evaluator.cc
  source/extensions/filters/common/expr/evaluator.h
  source/extensions/filters/http/header_to_metadata/BUILD
  source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc
  source/extensions/filters/http/jwt_authn/BUILD
  source/extensions/filters/http/jwt_authn/extractor.cc
  source/extensions/filters/http/lua/BUILD
  source/extensions/filters/http/lua/wrappers.cc
  test/common/http/BUILD
  test/common/http/header_map_impl_test.cc
  test/common/http/header_utility_test.cc
  test/extensions/common/wasm/BUILD
  test/extensions/filters/common/expr/context_test.cc
  test/extensions/filters/common/expr/evaluator_fuzz_test.cc
  test/extensions/filters/http/header_to_metadata/header_to_metadata_filter_test.cc
  test/extensions/filters/http/jwt_authn/extractor_test.cc
  test/extensions/filters/http/lua/wrappers_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/per_file_coverage.sh
  test/test_common/utility.h
Labels: cla: yes, size/XL

#270 Backport nack on was code cache miss.
  api/envoy/extensions/wasm/v3/wasm.proto
  generated_api_shadow/envoy/extensions/wasm/v3/wasm.proto
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/http/wasm/config_test.cc
  test/extensions/filters/network/wasm/config_test.cc
  test/test_common/wasm_base.h
Labels: cla: yes, size/M

#265 tracing: Fix spankind = CLIENT bug when sharedSpanContext is
  source/extensions/tracers/zipkin/tracer.cc
  test/extensions/tracers/zipkin/tracer_test.cc
Labels: cla: yes, size/M

#271 Fix Istio-2020-010
  VERSION
  docs/root/intro/version_history.rst
  include/envoy/http/BUILD
  include/envoy/http/header_map.h
  source/common/http/BUILD
  source/common/http/header_map_impl.cc
  source/common/http/header_map_impl.h
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/http/http1/codec_impl.cc
  source/common/runtime/BUILD
  source/common/runtime/runtime_features.cc
  source/common/runtime/runtime_features.h
  source/common/runtime/runtime_impl.cc
  source/extensions/common/wasm/context.cc
  source/extensions/filters/common/expr/BUILD
  source/extensions/filters/common/expr/context.cc
  source/extensions/filters/common/expr/context.h
  source/extensions/filters/common/expr/evaluator.cc
  source/extensions/filters/common/expr/evaluator.h
  source/extensions/filters/http/header_to_metadata/BUILD
  source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc
  source/extensions/filters/http/jwt_authn/BUILD
  source/extensions/filters/http/jwt_authn/extractor.cc
  source/extensions/filters/http/lua/BUILD
  source/extensions/filters/http/lua/wrappers.cc
  test/common/http/BUILD
  test/common/http/header_map_impl_test.cc
  test/common/http/header_utility_test.cc
  test/common/http/http1/codec_impl_test.cc
  test/extensions/common/wasm/BUILD
  test/extensions/filters/common/expr/context_test.cc
  test/extensions/filters/common/expr/evaluator_fuzz_test.cc
  test/extensions/filters/http/header_to_metadata/header_to_metadata_filter_test.cc
  test/extensions/filters/http/jwt_authn/extractor_test.cc
  test/extensions/filters/http/lua/wrappers_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/integration/protocol_integration_test.cc
Labels: cla: yes, size/XL

#272 Fix Istio-2020-010
  bazel/external/quiche.BUILD
  docs/root/intro/version_history.rst
  include/envoy/http/BUILD
  include/envoy/http/header_map.h
  source/common/http/BUILD
  source/common/http/async_client_impl.h
  source/common/http/header_map_impl.cc
  source/common/http/header_map_impl.h
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/http/http1/codec_impl.cc
  source/common/runtime/BUILD
  source/common/runtime/runtime_features.cc
  source/common/runtime/runtime_features.h
  source/common/runtime/runtime_impl.cc
  source/common/runtime/runtime_impl.h
  source/extensions/common/wasm/wasm.cc
  source/extensions/filters/common/expr/BUILD
  source/extensions/filters/common/expr/context.cc
  source/extensions/filters/common/expr/context.h
  source/extensions/filters/common/expr/evaluator.cc
  source/extensions/filters/common/expr/evaluator.h
  source/extensions/filters/http/header_to_metadata/BUILD
  source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc
  source/extensions/filters/http/jwt_authn/BUILD
  source/extensions/filters/http/jwt_authn/extractor.cc
  source/extensions/filters/http/lua/BUILD
  source/extensions/filters/http/lua/wrappers.cc
  source/extensions/filters/network/dubbo_proxy/hessian_utils.cc
  source/extensions/stat_sinks/hystrix/hystrix.cc
  test/common/http/BUILD
  test/common/http/async_client_impl_test.cc
  test/common/http/header_map_impl_test.cc
  test/common/http/header_utility_test.cc
  test/common/http/http1/codec_impl_test.cc
  test/extensions/common/wasm/BUILD
  test/extensions/filters/common/expr/context_test.cc
  test/extensions/filters/http/buffer/config_test.cc
  test/extensions/filters/http/dynamo/config_test.cc
  test/extensions/filters/http/header_to_metadata/header_to_metadata_filter_test.cc
  test/extensions/filters/http/jwt_authn/extractor_test.cc
  test/extensions/filters/http/lua/wrappers_test.cc
  test/extensions/filters/http/rbac/config_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/extensions/filters/network/rbac/config_test.cc
  test/integration/protocol_integration_test.cc
  tools/spelling_dictionary.txt
Labels: cla: yes, size/XL

#273 wasm: support list lookup in get_property (#13483)
  source/extensions/common/wasm/context.cc
  test/extensions/filters/http/wasm/test_data/test_cpp.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/S

#275 [Wasm] Add cluster metadata fallback and upstream host metadata (#13477)
  source/extensions/common/wasm/context.cc
  test/extensions/filters/http/wasm/test_data/test_cpp.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/M

#274 update opencensus
  bazel/repository_locations.bzl
Labels: cla: yes, size/XS

#276 listener: add match all filter chain (#13449)
  api/envoy/config/listener/v3/listener.proto
  api/envoy/config/listener/v3/listener_components.proto
  api/envoy/config/listener/v4alpha/listener.proto
  api/envoy/config/listener/v4alpha/listener_components.proto
  docs/root/configuration/listeners/lds.rst
  docs/root/intro/arch_overview/listeners/listeners_toc.rst
  docs/root/intro/arch_overview/listeners/network_filter_chain.rst
  generated_api_shadow/envoy/config/listener/v3/listener.proto
  generated_api_shadow/envoy/config/listener/v3/listener_components.proto
  generated_api_shadow/envoy/config/listener/v4alpha/listener.proto
  generated_api_shadow/envoy/config/listener/v4alpha/listener_components.proto
  source/extensions/filters/listener/tls_inspector/tls_inspector.cc
  source/server/filter_chain_manager_impl.cc
  source/server/filter_chain_manager_impl.h
  source/server/listener_impl.cc
  test/integration/xds_integration_test.cc
  test/server/filter_chain_benchmark_test.cc
  test/server/filter_chain_manager_impl_test.cc
  test/server/listener_manager_impl_test.cc
Labels: cla: yes, size/L

#277 fix: record recovered local address (#13581)
  source/server/connection_handler_impl.cc
  test/server/connection_handler_test.cc
Labels: cla: yes, size/S

#278 [release-1.8] Automated branching step 4
  CODEOWNERS
Labels: cla: yes, size/L

#279 cherry-pick of https://github.com/envoyproxy/envoy/pull/13739
  bazel/cel-cpp.patch
  bazel/repositories.bzl
Labels: cla: yes, size/M

#280 cherry-pick of https://github.com/envoyproxy/envoy/pull/13683
  source/common/router/router.cc
  test/integration/integration_test.cc
Labels: cla: yes, size/XS
