Repository istio/envoy, pull requests merged in 2020-04, with the labels that each got.

#194 zipkin: Fix wrongly rendered timestamp value (#10400)
  source/extensions/tracers/zipkin/span_buffer.cc
  source/extensions/tracers/zipkin/span_buffer.h
  source/extensions/tracers/zipkin/util.cc
  source/extensions/tracers/zipkin/util.h
  source/extensions/tracers/zipkin/zipkin_core_types.cc
  source/extensions/tracers/zipkin/zipkin_core_types.h
  test/extensions/tracers/zipkin/BUILD
  test/extensions/tracers/zipkin/span_buffer_test.cc
  test/extensions/tracers/zipkin/zipkin_core_types_test.cc
Labels: cla: yes, size/XL

#195 [release-1.6] manual cherry-pick of https://github.com/envoyproxy/env…
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/declare_property.proto
  source/extensions/common/wasm/foreign.cc
  source/extensions/common/wasm/null/sample_plugin/BUILD
  source/extensions/common/wasm/null/sample_plugin/plugin.cc
  source/extensions/common/wasm/wasm_state.cc
  source/extensions/common/wasm/wasm_state.h
  source/extensions/filters/common/expr/evaluator.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/L

#197 [release-1.6] cherry-pick of https://github.com/envoyproxy/envoy-wasm/pull/486
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
Labels: cla: yes, size/M

#198 Backport of fix to delay Envoy exit till the Wasm VM is done.
  include/envoy/server/BUILD
  include/envoy/server/wasm_config.h
  source/extensions/access_loggers/wasm/config.cc
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  source/extensions/filters/http/wasm/wasm_filter.cc
  source/extensions/filters/network/wasm/wasm_filter.cc
  source/extensions/wasm/config.cc
  source/server/server.cc
  source/server/wasm_config_impl.h
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
  test/extensions/filters/network/wasm/wasm_filter_test.cc
  test/extensions/wasm/config_test.cc
Labels: cla: yes, size/L

#196 [release-1.6] zipkin: Fix wrongly rendered timestamp value (#10400)
  source/extensions/tracers/zipkin/span_buffer.cc
  source/extensions/tracers/zipkin/span_buffer.h
  source/extensions/tracers/zipkin/util.cc
  source/extensions/tracers/zipkin/util.h
  source/extensions/tracers/zipkin/zipkin_core_types.cc
  source/extensions/tracers/zipkin/zipkin_core_types.h
  test/extensions/tracers/zipkin/BUILD
  test/extensions/tracers/zipkin/span_buffer_test.cc
  test/extensions/tracers/zipkin/zipkin_core_types_test.cc
Labels: cla: yes, size/XL

#199 [release-1.4] empty strict dns cluster fix cherry-pick envoyproxy #10728
  source/common/upstream/strict_dns_cluster.cc
  test/common/upstream/upstream_impl_test.cc
Labels: cla: yes, size/M

#200 [release-1.5] empty strict dns cluster fix cherry-pick envoyproxy #10728
  source/common/upstream/strict_dns_cluster.cc
  test/common/upstream/upstream_impl_test.cc
Labels: cla: yes, size/M

#202 Add Code cache TTL and tests.
  source/common/config/datasource.h
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  test/extensions/access_loggers/wasm/config_test.cc
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/http/wasm/config_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
  test/extensions/filters/network/wasm/config_test.cc
Labels: cla: yes, size/XL

#203 update code owner for 1.6
  CODEOWNERS
Labels: cla: yes, size/L
