Repository istio/envoy, pull requests merged in 2020-03, with the labels that each got.

#170 wasm: restore and fix the Wasm Service. (#440)
  include/envoy/server/wasm.h
  include/envoy/server/wasm_config.h
  source/extensions/wasm/config.cc
  source/extensions/wasm/config.h
  source/server/server.cc
  source/server/server.h
  test/extensions/wasm/config_test.cc
Labels: cla: yes, size/M

#173 tls_inspector: enable TLSv1.3. (#118)
  docs/root/intro/version_history.rst
  source/extensions/filters/listener/tls_inspector/tls_inspector.cc
  source/extensions/filters/listener/tls_inspector/tls_inspector.h
  test/extensions/filters/listener/tls_inspector/tls_inspector_benchmark.cc
  test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc
  test/extensions/filters/listener/tls_inspector/tls_utility.cc
  test/extensions/filters/listener/tls_inspector/tls_utility.h
Labels: cla: yes, size/M

#174 sds: fix combined validation context validation bypassing (#114)
  source/common/secret/sds_api.h
  source/extensions/transport_sockets/tls/context_config_impl.cc
  test/integration/sds_dynamic_integration_test.cc
Labels: cla: yes, size/L

#171 buffer: release empty slices after commit (#116)
  include/envoy/buffer/buffer.h
  source/common/buffer/buffer_impl.cc
  source/common/buffer/buffer_impl.h
  test/common/buffer/owned_impl_test.cc
Labels: cla: yes, size/L

#172 buffer: draining any zero byte fragments (#9837) (#109)
  source/common/buffer/buffer_impl.cc
  test/common/buffer/owned_impl_test.cc
Labels: cla: yes, size/S

#178 buffer: Force copy when appending small slices to OwnedImpl buffer to…
  docs/root/intro/version_history.rst
  source/common/buffer/buffer_impl.cc
  source/common/buffer/buffer_impl.h
  test/common/buffer/owned_impl_test.cc
  test/common/buffer/zero_copy_input_stream_test.cc
  test/common/http/http1/codec_impl_test.cc
Labels: cla: yes, size/L

#180 Revert STS from 1.4 with cherry picks of integration and stress test fixes.
  api/envoy/api/v2/core/grpc_service.proto
  api/envoy/api/v3alpha/core/grpc_service.proto
  api/wasm/cpp/proxy_wasm_api.h
  api/wasm/cpp/proxy_wasm_intrinsics.pb.cc
  api/wasm/cpp/proxy_wasm_intrinsics.pb.h
  api/wasm/cpp/proxy_wasm_intrinsics.proto
  api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.cc
  api/wasm/cpp/proxy_wasm_intrinsics_lite.pb.h
  api/wasm/cpp/proxy_wasm_intrinsics_lite.proto
  bazel/dependency_imports.bzl
  bazel/envoy_test.bzl
  bazel/grpc-protoinfo-1.patch
  bazel/grpc-protoinfo-2.patch
  bazel/grpc-protoinfo-3.patch
  bazel/grpc-rename-gettid.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  bazel/upb.patch
  source/common/grpc/google_grpc_creds_impl.cc
  source/common/http/async_client_impl.h
  source/extensions/tracers/opencensus/config.cc
  source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
  source/extensions/tracers/opencensus/opencensus_tracer_impl.h
  test/common/grpc/google_grpc_creds_test.cc
  test/extensions/filters/common/expr/context_test.cc
  test/extensions/filters/http/wasm/BUILD
  test/extensions/tracers/opencensus/tracer_test.cc
  test/integration/BUILD
  test/stress/BUILD
  test/stress/stress_test_common.cc
  test/stress/stress_test_common.h
Labels: cla: yes, size/XXL

#179 network: draining the buffer on close (#9870) (#110)
  source/common/network/connection_impl.cc
  test/common/network/connection_impl_test.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
Labels: cla: yes, size/S

#181 http: adding response flood protection (#113)
  docs/root/configuration/http/http_conn_man/stats.rst
  docs/root/intro/version_history.rst
  source/common/http/http1/codec_impl.cc
  source/common/http/http1/codec_impl.h
  source/common/runtime/runtime_features.cc
  source/common/runtime/runtime_impl.cc
  test/common/http/http1/codec_impl_test.cc
  test/integration/integration_admin_test.cc
  test/integration/integration_test.cc
Labels: cla: yes, size/L

#177 wasm: Add API to get buffered body data. (#437)
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  test/extensions/filters/http/wasm/test_data/Makefile
  test/extensions/filters/http/wasm/test_data/body_cpp.cc
  test/extensions/filters/http/wasm/test_data/body_cpp.wasm
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/L

#184 wasm: add proxy_set_buffer_bytes. (#442)
  api/wasm/cpp/proxy_wasm_api.h
  api/wasm/cpp/proxy_wasm_externs.h
  api/wasm/cpp/proxy_wasm_intrinsics.js
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/exports.cc
  source/extensions/common/wasm/exports.h
  source/extensions/common/wasm/null/wasm_api_impl.h
  source/extensions/common/wasm/wasm.cc
  test/extensions/filters/http/wasm/test_data/body_cpp.cc
  test/extensions/filters/http/wasm/test_data/body_cpp.wasm
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: cla: yes, size/L

#183 Add getContext in null_plugin (#447)
  source/extensions/common/wasm/null/null_plugin.cc
  source/extensions/common/wasm/null/null_plugin.h
  source/extensions/common/wasm/null/wasm_api_impl.h
Labels: cla: yes, size/S

#182 1.4.6 security fixes
  docs/root/configuration/http/http_conn_man/stats.rst
  docs/root/intro/version_history.rst
  include/envoy/buffer/buffer.h
  source/common/buffer/buffer_impl.cc
  source/common/buffer/buffer_impl.h
  source/common/http/http1/codec_impl.cc
  source/common/http/http1/codec_impl.h
  source/common/network/connection_impl.cc
  source/common/runtime/runtime_features.cc
  source/common/runtime/runtime_impl.cc
  source/common/secret/sds_api.h
  source/extensions/filters/listener/tls_inspector/tls_inspector.cc
  source/extensions/filters/listener/tls_inspector/tls_inspector.h
  source/extensions/transport_sockets/tls/context_config_impl.cc
  test/common/buffer/owned_impl_test.cc
  test/common/buffer/zero_copy_input_stream_test.cc
  test/common/http/http1/codec_impl_test.cc
  test/common/network/connection_impl_test.cc
  test/extensions/filters/listener/tls_inspector/tls_inspector_benchmark.cc
  test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc
  test/extensions/filters/listener/tls_inspector/tls_utility.cc
  test/extensions/filters/listener/tls_inspector/tls_utility.h
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
  test/integration/integration_admin_test.cc
  test/integration/integration_test.cc
  test/integration/sds_dynamic_integration_test.cc
Labels: cla: yes, do-not-merge/work-in-progress, size/XL

#187 [Release-1.5] Fix memory leak in TCP
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
Labels: cla: yes, size/M

#188 [Release-1.5] Add ClusterInfo as a property in StreamInfo (#10432)
  include/envoy/stream_info/stream_info.h
  source/common/http/conn_manager_impl.cc
  source/common/stream_info/stream_info_impl.h
  source/common/tcp_proxy/tcp_proxy.cc
  test/common/stream_info/stream_info_impl_test.cc
  test/common/stream_info/test_util.h
  test/common/tcp_proxy/tcp_proxy_test.cc
  test/mocks/stream_info/mocks.h
Labels: cla: yes, size/M

#189 [Release-1.5] Use ClusterInfo from streaminfo to get clustername too
  source/extensions/common/wasm/context.cc
Labels: cla: yes, size/XS

#190 Fixes ASSERT failure and infinite loop when attempting to unset readDisable state on a closed connection
  source/common/http/http1/codec_impl.cc
  source/common/network/connection_impl.cc
  test/common/network/connection_impl_test.cc
  test/integration/integration_test.cc
Labels: cla: yes, size/M
