Repository istio/envoy, pull requests merged in 2020-11, with the labels that each got.

#281 Sds backport
  docs/root/version_history/current.rst
  include/envoy/network/transport_socket.h
  include/envoy/ssl/context_config.h
  source/common/network/raw_buffer_socket.cc
  source/common/network/raw_buffer_socket.h
  source/common/runtime/runtime_features.cc
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/cluster_manager_impl.h
  source/extensions/quic_listeners/quiche/quic_transport_socket_factory.h
  source/extensions/transport_sockets/alts/tsi_socket.cc
  source/extensions/transport_sockets/alts/tsi_socket.h
  source/extensions/transport_sockets/proxy_protocol/proxy_protocol.cc
  source/extensions/transport_sockets/proxy_protocol/proxy_protocol.h
  source/extensions/transport_sockets/tap/tap.cc
  source/extensions/transport_sockets/tap/tap.h
  source/extensions/transport_sockets/tls/context_config_impl.cc
  source/extensions/transport_sockets/tls/context_config_impl.h
  source/extensions/transport_sockets/tls/ssl_socket.cc
  source/extensions/transport_sockets/tls/ssl_socket.h
  test/common/upstream/BUILD
  test/common/upstream/cluster_manager_impl_test.cc
  test/common/upstream/transport_socket_matcher_test.cc
  test/extensions/transport_sockets/proxy_protocol/proxy_protocol_test.cc
  test/extensions/transport_sockets/tls/context_impl_test.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
  test/integration/ads_integration_test.cc
  test/integration/xfcc_integration_test.cc
  test/mocks/network/transport_socket.h
  test/mocks/ssl/mocks.h
Labels: cla: yes, size/L

#282 [Release-1.8] Add Connection_Termination_Details as a CEL property (#13821)
  docs/root/intro/arch_overview/security/rbac_filter.rst
  docs/root/version_history/current.rst
  source/extensions/filters/common/expr/context.cc
  source/extensions/filters/common/expr/context.h
  test/extensions/filters/common/expr/context_test.cc
Labels: cla: yes, size/S

#283 Revert "Sds backport (#281)"
  include/envoy/network/transport_socket.h
  include/envoy/ssl/context_config.h
  source/common/network/raw_buffer_socket.cc
  source/common/network/raw_buffer_socket.h
  source/common/runtime/runtime_features.cc
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/cluster_manager_impl.h
  source/extensions/quic_listeners/quiche/quic_transport_socket_factory.h
  source/extensions/transport_sockets/alts/tsi_socket.cc
  source/extensions/transport_sockets/alts/tsi_socket.h
  source/extensions/transport_sockets/proxy_protocol/proxy_protocol.cc
  source/extensions/transport_sockets/proxy_protocol/proxy_protocol.h
  source/extensions/transport_sockets/tap/tap.cc
  source/extensions/transport_sockets/tap/tap.h
  source/extensions/transport_sockets/tls/context_config_impl.cc
  source/extensions/transport_sockets/tls/context_config_impl.h
  source/extensions/transport_sockets/tls/ssl_socket.cc
  source/extensions/transport_sockets/tls/ssl_socket.h
  test/common/upstream/BUILD
  test/common/upstream/cluster_manager_impl_test.cc
  test/common/upstream/transport_socket_matcher_test.cc
  test/extensions/transport_sockets/proxy_protocol/proxy_protocol_test.cc
  test/extensions/transport_sockets/tls/context_impl_test.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
  test/integration/ads_integration_test.cc
  test/integration/xfcc_integration_test.cc
  test/mocks/network/transport_socket.h
  test/mocks/ssl/mocks.h
Labels: cla: yes, size/L

#285 [1.8] fix cluster early warm up
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/cluster_manager_impl.h
  test/common/upstream/cluster_manager_impl_test.cc
  test/integration/ads_integration.cc
  test/integration/ads_integration.h
  test/integration/ads_integration_test.cc
  test/integration/base_integration_test.cc
Labels: cla: yes, size/L

#284 Proxy-Wasm mega backport
  .bazelrc
  bazel/external/wee8.BUILD
  bazel/external/wee8.genrule_cmd
  bazel/external/wee8.patch
  bazel/foreign_cc/BUILD
  bazel/foreign_cc/zlib.patch
  bazel/repository_locations.bzl
  bazel/wasm/wasm.bzl
  docs/root/version_history/current.rst
  source/extensions/common/wasm/context.cc
  source/extensions/transport_sockets/tls/ssl_handshaker.h
  source/extensions/transport_sockets/tls/ssl_socket.cc
  test/extensions/bootstrap/wasm/wasm_test.cc
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/common/wasm/wasm_vm_test.cc
  test/extensions/filters/http/wasm/BUILD
  test/extensions/filters/http/wasm/test_data/BUILD
  test/extensions/filters/http/wasm/test_data/resume_call_rust.rs
  test/extensions/filters/http/wasm/test_data/test_resume_call_cpp.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
  test/extensions/filters/network/wasm/wasm_filter_test.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
  test/tools/wee8_compile/wee8_compile.cc
  tools/code_format/check_format.py
Labels: cla: yes, size/XL
