Repository istio/envoy, pull requests merged in 2020-08, with the labels that each got.

#249 Defer sendLocalReply() to prevent reentrant calls.
  source/extensions/common/wasm/context.cc
Labels: cla: yes, size/S

#248 Support multiple versions of the Proxy-Wasm ABI.
  bazel/repository_locations.bzl
  source/extensions/common/wasm/context.h
  test/extensions/common/wasm/test_data/test_cpp.cc
Labels: cla: yes, size/S

#250 Reenable LTO which has a huge effect on performance.
  bazel/repository_locations.bzl
  test/extensions/bootstrap/wasm/test_data/segv_cpp.cc
  test/extensions/common/wasm/test_data/test_cpp.cc
Labels: cla: yes, size/S

#252 cherry-pick of https://github.com/envoyproxy/envoy/pull/12479
  source/common/filter/http/filter_config_discovery_impl.cc
  source/common/filter/http/filter_config_discovery_impl.h
  test/integration/BUILD
  test/integration/extension_discovery_integration_test.cc
  test/integration/filters/BUILD
  test/integration/filters/set_response_code_filter.cc
  test/integration/filters/set_response_code_filter_config.proto
Labels: cla: yes, size/L

#253 Fix header corruption in sendLocalResponse (#606)
  source/extensions/common/wasm/context.cc
Labels: cla: yes, size/S

#254 Report correct body size in buffered mode.
  source/extensions/common/wasm/context.cc
Labels: cla: yes, size/XS

#255 Fix compatibility with Proxy-Wasm ABI v0.1.0.
  bazel/repository_locations.bzl
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
Labels: cla: yes, size/S

#257 Fix C++14 compatibility.
  bazel/repository_locations.bzl
Labels: cla: yes, size/XS

#258 Update antlr4 dep for cel, to fix crash
  bazel/dependency_imports.bzl
  bazel/repositories.bzl
Labels: cla: yes, size/XS

#259 Update antlr16
  WORKSPACE
  bazel/repositories.bzl
Labels: cla: yes, size/XS

#260 [Release-1.7] Fix onLog
  source/extensions/common/wasm/context.cc
Labels: cla: yes, size/XS

#261 Make opencensus Stackdriver exporter respects initial_metadata option…
  bazel/repository_locations.bzl
  source/extensions/tracers/opencensus/opencensus_tracer_impl.cc
  test/extensions/tracers/opencensus/config_test.cc
Labels: cla: yes, size/S
