Repository istio/envoy, pull requests merged in 2021-02, with the labels that each got.

#297 release-1.7: Disable building Envoy filter example in CI
  ci/build_setup.sh
Labels: cla: yes, size/XS

#296 release-1.8: Disable building Envoy filter example in CI
  ci/build_setup.sh
Labels: cla: yes, size/XS

#298 release-1.9: Disable building Envoy filter example in CI
  ci/build_setup.sh
Labels: cla: yes, size/XS

#294 Merge envoy/release/v1.16 into release-1.8
  VERSION
  ci/Dockerfile-envoy-google-vrp
  configs/google-vrp/supervisor.conf
  docs/root/version_history/current.rst
  docs/root/version_history/v1.16.1.rst
  docs/root/version_history/v1.16.2.rst
  docs/root/version_history/version_history.rst
  include/envoy/registry/registry.h
  source/common/config/new_grpc_mux_impl.cc
  source/common/http/utility.cc
  source/common/init/manager_impl.cc
  source/common/router/scoped_rds.cc
  source/extensions/clusters/aggregate/cluster.cc
  source/extensions/filters/http/lua/wrappers.h
  source/server/admin/config_dump_handler.cc
  source/server/filter_chain_manager_impl.cc
  test/common/http/utility_test.cc
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
  test/extensions/filters/http/lua/lua_filter_test.cc
  test/extensions/transport_sockets/tls/BUILD
  test/extensions/transport_sockets/tls/context_impl_test.cc
  test/extensions/transport_sockets/tls/gen_unittest_certs.sh
  test/extensions/transport_sockets/tls/handshaker_test.cc
  test/extensions/transport_sockets/tls/ocsp/BUILD
  test/extensions/transport_sockets/tls/ocsp/ocsp_test.cc
  test/extensions/transport_sockets/tls/ocsp/test_data/BUILD
  test/extensions/transport_sockets/tls/ocsp/test_data/README.md
  test/extensions/transport_sockets/tls/ocsp/test_data/ca_cert.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/ca_key.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/certs.sh
  test/extensions/transport_sockets/tls/ocsp/test_data/ecdsa_cert.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/ecdsa_key.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/ecdsa_ocsp_req.der
  test/extensions/transport_sockets/tls/ocsp/test_data/ecdsa_ocsp_resp.der
  test/extensions/transport_sockets/tls/ocsp/test_data/good_cert.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/good_key.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/good_ocsp_req.der
  test/extensions/transport_sockets/tls/ocsp/test_data/good_ocsp_resp.der
  test/extensions/transport_sockets/tls/ocsp/test_data/good_ocsp_resp_details.txt
  test/extensions/transport_sockets/tls/ocsp/test_data/intermediate_ca_cert.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/intermediate_ca_key.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/multiple_cert_ocsp_req.der
  test/extensions/transport_sockets/tls/ocsp/test_data/multiple_cert_ocsp_resp.der
  test/extensions/transport_sockets/tls/ocsp/test_data/responder_key_hash_ocsp_req.der
  test/extensions/transport_sockets/tls/ocsp/test_data/responder_key_hash_ocsp_resp.der
  test/extensions/transport_sockets/tls/ocsp/test_data/revoked_cert.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/revoked_key.pem
  test/extensions/transport_sockets/tls/ocsp/test_data/revoked_ocsp_req.der
  test/extensions/transport_sockets/tls/ocsp/test_data/revoked_ocsp_resp.der
  test/extensions/transport_sockets/tls/ocsp/test_data/unknown_ocsp_req.der
  test/extensions/transport_sockets/tls/ocsp/test_data/unknown_ocsp_resp.der
  test/extensions/transport_sockets/tls/ssl_certs_test.h
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
  test/extensions/transport_sockets/tls/test_data/certs.sh
  test/extensions/transport_sockets/tls/test_data/unittest_cert.cfg
  test/extensions/transport_sockets/tls/test_data/unittest_cert.pem
  test/extensions/transport_sockets/tls/test_data/unittest_cert_info.h
  test/extensions/transport_sockets/tls/test_data/unittest_key.pem
  test/integration/integration_test.cc
  test/mocks/thread_local/mocks.h
Labels: cla: yes, size/XXL

#299 Merge envoyproxy/envoy:release/v1.17 into release-1.9.
  .azure-pipelines/pipelines.yml
  .github/workflows/get_build_targets.sh
  VERSION
  bazel/repository_locations.bzl
  ci/do_ci.sh
  ci/filter_example_setup.sh
  ci/verify_examples.sh
  configs/requirements.txt
  docs/root/version_history/current.rst
  docs/root/version_history/v1.17.0.rst
  docs/root/version_history/version_history.rst
  examples/websocket/verify.sh
  source/common/event/scaled_range_timer_manager_impl.cc
  source/common/event/scaled_range_timer_manager_impl.h
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  source/extensions/common/wasm/wasm_extension.cc
  source/extensions/common/wasm/wasm_extension.h
  source/extensions/filters/http/wasm/wasm_filter.h
  source/extensions/filters/network/kafka/requirements.txt
  source/extensions/filters/network/wasm/wasm_filter.h
  source/extensions/transport_sockets/tls/context_impl.cc
  test/common/event/scaled_range_timer_manager_impl_test.cc
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/network/wasm/config_test.cc
  test/extensions/transport_sockets/tls/context_impl_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: cla: yes, do-not-merge/work-in-progress, size/L

#303 jwt_authn: fix a bug where JWT with wrong issuer is allowed in allow_missing case
  VERSION
  docs/root/version_history/current.rst
  source/extensions/filters/http/jwt_authn/verifier.cc
  test/extensions/filters/http/jwt_authn/all_verifier_test.cc
  test/extensions/filters/http/jwt_authn/group_verifier_test.cc
Labels: cla: yes, size/M
