Repository istio/envoy, pull requests merged in 2021-01, with the labels that each got.

#291 Set release managers as CODEOWNERS for release-1.9
  CODEOWNERS
Labels: cla: yes, size/L

#292 local ratelimit: Add descriptor support in HTTP Local Rate Limiting (…
  api/envoy/config/route/v3/route_components.proto
  api/envoy/config/route/v4alpha/route_components.proto
  api/envoy/extensions/common/ratelimit/v3/ratelimit.proto
  api/envoy/extensions/filters/http/local_ratelimit/v3/BUILD
  api/envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto
  docs/root/api-v3/config/common/common.rst
  docs/root/configuration/http/http_filters/local_rate_limit_filter.rst
  generated_api_shadow/envoy/config/route/v3/route_components.proto
  generated_api_shadow/envoy/config/route/v4alpha/route_components.proto
  generated_api_shadow/envoy/extensions/common/ratelimit/v3/ratelimit.proto
  generated_api_shadow/envoy/extensions/filters/http/local_ratelimit/v3/BUILD
  generated_api_shadow/envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto
  include/envoy/ratelimit/ratelimit.h
  include/envoy/router/router_ratelimit.h
  source/common/router/router_ratelimit.cc
  source/common/router/router_ratelimit.h
  source/extensions/filters/common/local_ratelimit/BUILD
  source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.cc
  source/extensions/filters/common/local_ratelimit/local_ratelimit_impl.h
  source/extensions/filters/http/local_ratelimit/BUILD
  source/extensions/filters/http/local_ratelimit/config.cc
  source/extensions/filters/http/local_ratelimit/local_ratelimit.cc
  source/extensions/filters/http/local_ratelimit/local_ratelimit.h
  source/extensions/filters/network/local_ratelimit/local_ratelimit.cc
  source/extensions/filters/network/local_ratelimit/local_ratelimit.h
  source/extensions/rate_limit_descriptors/expr/config.cc
  test/common/router/router_ratelimit_test.cc
  test/extensions/filters/common/local_ratelimit/local_ratelimit_test.cc
  test/extensions/filters/http/local_ratelimit/BUILD
  test/extensions/filters/http/local_ratelimit/config_test.cc
  test/extensions/filters/http/local_ratelimit/filter_test.cc
  test/mocks/ratelimit/mocks.h
  test/mocks/router/mocks.h
Labels: cla: yes, size/XXL

#293 wasm: fix network leak (#13836)
  source/extensions/common/wasm/context.cc
  test/integration/BUILD
Labels: cla: yes, size/XS
