Repository istio/envoy, pull requests merged in 2021-08, with the labels that each got.

#329 jwt_authn: implementation of www-authenticate header (#16216) (#17441)
  docs/root/version_history/current.rst
  source/common/http/utility.cc
  source/common/http/utility.h
  source/common/tracing/http_tracer_impl.cc
  source/extensions/filters/http/jwt_authn/filter.cc
  source/extensions/filters/http/jwt_authn/filter.h
  test/common/http/utility_test.cc
  test/common/tracing/http_tracer_impl_test.cc
  test/extensions/filters/http/jwt_authn/filter_integration_test.cc
Labels: cla: yes, size/L, tide/merge-method-merge, ok-to-test

#330 Updated MarkupSafe hash in requirements.txt (#17263)
  configs/requirements.txt
  docs/requirements.txt
  source/extensions/filters/network/kafka/requirements.txt
Labels: cla: yes, size/XS, tide/merge-method-merge, ok-to-test

#331 [release-1.9] August 2021 security patches
  docs/root/version_history/current.rst
  source/common/http/conn_manager_utility.cc
  source/common/http/filter_manager.cc
  source/common/http/filter_manager.h
  source/common/http/http2/codec_impl.cc
  source/common/http/http2/codec_impl.h
  source/common/router/router.cc
  source/common/runtime/runtime_features.cc
  source/extensions/filters/common/ext_authz/check_request_utils.cc
  test/common/http/conn_manager_utility_test.cc
  test/common/http/http2/codec_impl_test.cc
  test/common/router/router_test.cc
  test/extensions/filters/common/ext_authz/check_request_utils_test.cc
  test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/integration/BUILD
  test/integration/base_integration_test.h
  test/integration/fake_upstream.cc
  test/integration/fake_upstream.h
  test/integration/filters/BUILD
  test/integration/filters/add_body_filter.cc
  test/integration/filters/add_body_filter.proto
  test/integration/filters/crash_filter.cc
  test/integration/filters/crash_filter.proto
  test/integration/http2_flood_integration_test.cc
  test/integration/protocol_integration_test.cc
  test/integration/redirect_integration_test.cc
  test/test_common/utility.cc
Labels: cla: yes, size/XXL, tide/merge-method-merge
