Repository istio/envoy, pull requests merged in 2021-04, with the labels that each got.

#314 Update for envoy cves (april 15, 2021)
  docs/root/configuration/http/http_conn_man/stats.rst
  source/common/grpc/common.cc
  source/common/grpc/common.h
  source/common/http/http2/codec_impl.cc
  source/common/http/http2/codec_impl.h
  test/common/grpc/common_test.cc
  test/common/http/http2/BUILD
  test/common/http/http2/http2_frame.cc
  test/common/http/http2/http2_frame.h
  test/common/router/router_test.cc
  test/integration/fake_upstream.cc
  test/integration/fake_upstream.h
  test/integration/http2_integration_test.cc
  test/integration/integration.cc
  test/integration/integration.h
  test/integration/integration_admin_test.cc
Labels: cla: yes, do-not-merge/work-in-progress, size/L

#313 Cherry-pick GREENPIG for 1.9
  docs/root/configuration/http/http_conn_man/stats.rst
  source/common/grpc/common.cc
  source/common/grpc/common.h
  source/common/http/http2/codec_impl.cc
  source/common/http/http2/codec_stats.h
  source/extensions/transport_sockets/tls/context_impl.cc
  source/extensions/transport_sockets/tls/ssl_socket.cc
  test/common/grpc/common_test.cc
  test/common/http/conn_manager_impl_test.cc
  test/common/http/http2/http2_frame.cc
  test/common/http/http2/http2_frame.h
  test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
  test/integration/http2_integration_test.cc
  test/integration/integration_stream_decoder.cc
  test/integration/integration_stream_decoder.h
Labels: cla: yes, size/L

#312 Cherry-pick fix for greenpig
  docs/root/configuration/http/http_conn_man/stats.rst
  source/common/grpc/common.cc
  source/common/grpc/common.h
  source/common/http/http2/codec_impl.cc
  source/common/http/http2/codec_impl_legacy.cc
  source/common/http/http2/codec_stats.h
  source/extensions/transport_sockets/tls/context_impl.cc
  source/extensions/transport_sockets/tls/ssl_socket.cc
  test/common/grpc/common_test.cc
  test/common/http/conn_manager_impl_test.cc
  test/common/http/http2/http2_frame.cc
  test/common/http/http2/http2_frame.h
  test/common/router/router_test.cc
  test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
  test/integration/http2_integration_test.cc
  test/integration/integration_stream_decoder.cc
  test/integration/integration_stream_decoder.h
  test/integration/stats_integration_test.cc
Labels: cla: yes, size/L

#310 Add release-manager-1.10 back as codeowners
  CODEOWNERS
Labels: cla: yes, size/L

#318 Merge envoyproxy/envoy release/v1.14.7 tag
  VERSION
  docs/root/intro/version_history.rst
Labels: cla: yes, size/XS
